name: social_chat_bot_assistant
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #firebase_auth: ^0.18.4+1
  #flutter_signin_button: ^1.0.0
  #firebase_core: ^0.5.3
  #google_sign_in: ^4.5.9
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  provider: ^4.0.4
  #firebase_storage: ^3.1.5
  image_picker: ^0.6.4
  datetime_picker_formfield: ^1.0.0
  #flutter_local_notifications: ^1.4.1
  path_provider: ^0.5.0+1
  flutter_swiper: ^1.1.6
  curved_navigation_bar: ^0.3.2
  giffy_dialog: ^1.7.0
  flutter_redux: ^0.6.0
  percent_indicator: ^2.1.3
  fl_chart: ^0.9.3
  flutter_dialogflow: ^0.1.3
  http: ^0.12.0+2
  flutter_spinkit: ^4.1.2+1
  url_launcher: ^5.4.7
  flutter_speed_dial: ^1.2.1
  folding_cell: ^0.1.2
  flutube: ^0.8.3
  flutter_svg: ^0.19.1
  bubble: ^1.1.9+1
  flutter_dialogflow_v2: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/telecomchatbot-skxa-2b87d5049ce5.json
   # - assets/transport-agent-gpgv-149fd6638fbf.json
  #  - assets/services/transport-agent-lost-something.json
    #- assets/lost-something-plgg-678667f69a6c.json
    - assets/electricity-other-complai-tsdh-3a6737d1a7a7.json
    - assets/electricity-power-schedul-tsbv-701136c4a6d8.json
    - assets/electricity-sudden_power_failure.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster
      fonts:
       - asset: fonts/Lobster-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
